# Generated by Django 5.2.5 on 2025-08-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Список тегов'},
        ),
        migrations.AlterModelOptions(
            name='wallpaper',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Список обоев'},
        ),
    ]
