# Generated by Django 5.2.5 on 2025-08-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walls', '0002_alter_tags_options_alter_wallpaper_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='tag',
        ),
        migrations.AddField(
            model_name='wallpaper',
            name='tags',
            field=models.ManyToManyField(to='walls.tags'),
        ),
    ]
